name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-07-09
          components: clippy,rust-src,rustfmt
      - run: cargo fmt --all -- --check
      - run: cargo test --locked
      - run: cargo clippy --locked --all-targets -- -D warnings
      - run: cargo check -Zbuild-std=core --locked --target riscv32imfc-unknown-none-elf
      - run: cargo package --locked --no-verify
